### ISSUE TITLE
rucio-client-container should be a sub-repo of ESCAPE-WP2/containers

### ISSUE THREAD

**Issue by riccardodimaria** [ESCAPE-WP2/Rucio-Client-Containers#1]
Please rename `rucio-client-container` as `rucio-client` and move it into `ESCAPE-WP2/containers`.
Please improve documentation for non-experts, providing context.

**Comment by rizart** [comment]
Please move it to `ESCAPE-WP2/containers/rucio/`.

**Comment by ygrange** [comment]
Seems like the changes we propose will be merged upstream so then we can clean up over here. I would propose to have a simple Dockerfile which pulls in the lsc and vomses file. Then the UI containe with Dirac could be derived from this one.

**Comment by robbarnsley** [comment]
I've duplicated your effort here rearranging the repo for those upstream changes @ygrange, sorry about that!
