### ISSUE TITLE
bash: register-python-argcomplete: command not found

### ISSUE THREAD

**Issue by ygrange** [ESCAPE-WP2/Rucio-Client-Containers#39]
When I run the Singularity container with Rucio, it starts with the two lines:

```
bash: register-python-argcomplete: command not found
bash: register-python-argcomplete: command not found
```

I think this is probably a missing dependency and may be fairly easy to fix.

**Comment by ygrange** [comment]
I found out how to fix it, by installing the python-argcomplete package. I wonder whether this should be applied here or upstream. Also python-argcomplete is a python2 package so I am not even sure if this is completely what we want here... So basically any dsiscussion would be nice :)

**Comment by robbarnsley** [comment]
think this is almost certainly for the upstream image..

https://github.com/rucio/containers/blob/master/clients/Dockerfile#L39
https://github.com/rucio/containers/blob/master/clients/init_rucio.sh#L14

**Comment by ygrange** [comment]
https://github.com/rucio/containers/issues/169
(I will close this now)
